# /etc/jail.conf -- learning jail
# Chapter 17: Your First Jail

# Global defaults
exec.start = "/bin/sh /etc/rc";
exec.stop = "/bin/sh /etc/rc.shutdown";
exec.clean;
mount.devfs;

# Learning jail
cargo-bay-1 {
    host.hostname = "cargo-bay-1";
    path = "/zroot/jails/cargo-bay-1";
    ip4 = inherit;
    ip6 = disable;
    persist;
}
