# /etc/rc.conf -- enterprise base configuration
# Chapter 16: From Zero to Server

clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="enterprise"
keymap="de.noacc.kbd"
ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
moused_nondefault_enable="NO"
dumpdev="AUTO"
zfs_enable="YES"
