# Proxy -- the only jail with network access
# Chapter 19: Jails in Production

proxy-caddy {
    ip4.addr = 10.0.2.16;
    ip6 = disable;
    host.hostname = "proxy-caddy";
    path = "/zroot/jails/proxy-caddy";
    mount.fstab = "/etc/fstab.proxy-caddy";
    securelevel = 0;
}
