# Hardened global defaults -- inherited by every jail
# Chapter 19: Jails in Production

* {
    ip4 = disable;
    ip6 = disable;
    persist;
    host.hostname = "$name";
    path = "/zroot/jails/$name";
    mount.fstab = "/etc/fstab.$name";
    allow.raw_sockets = 0;
    allow.set_hostname = 0;
    allow.sysvipc = 0;
    allow.mount = 0;
    children.max = 0;
    enforce_statfs = 2;
    securelevel = 2;
    sysvshm = new;
    sysvsem = new;
    sysvmsg = new;
}
